variables:
- name: DefaultBuildConfiguration
  value: Debug
- name: DefaultBuildPlatform
  value: 'any cpu'
- name: ApkName
  value: AndroidControlGallery.AndroidControlGallery.apk
- name: IpaName
  value: XamarinFormsControlGalleryiOS.ipa
- name: SolutionFile
  value: Xamarin.Forms.sln
- name: BuildVersion
  value: $[counter('nuget-counter', 126)]
- name: BuildVersion42
  value: $[counter('xf-nuget-counter', 992000)]
- name: BuildVersion43
  value: $[counter('xf-nuget-counter', 992000)]
- name: BuildVersion44
  value: $[counter('xf-nuget-counter', 992000)]
- name: NUGET_VERSION
  value: 5.4.0
- name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
  value: true
- name: DOTNET_VERSION
  value: 3.1.100

resources:
  repositories:
    - repository: xamarin-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin

trigger:
  branches:
    include:
    - master
    - 3.*
    - 4.*
  tags:
    include:
    - '*'
  paths:
    exclude:
    - README.md

pr:
  autoCancel: false
  branches:
    include:
    - master
    - 4.*
    - 3.*

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master

jobs:
- template: build/steps/build-windows.yml
  parameters:
    name: win
    displayName: Build Windows Phase
    vmImage: $(vs2019VmImage)
    vmPool: $(vs2019VmPool)
    provisionatorPath : 'build/provisioning/provisioning.csx'

- template: build/steps/build-android.yml
  parameters:
    name: android_legacy
    displayName: Build Android [Legacy Renderers]
    vmImage: $(macOSXVmImage)
    targetFolder: Xamarin.Forms.ControlGallery.Android/legacyRenderers/
    androidProjectArguments: '/t:"Rebuild;SignAndroidPackage" /p:ANDROID_RENDERERS="LEGACY" /bl:$(Build.ArtifactStagingDirectory)/android-legacy.binlog'
    buildConfiguration: $(AndroidBuildConfiguration)
    provisionatorPath : 'build/provisioning/provisioning.csx'

- template: build/steps/build-android.yml
  parameters:
    name: android_preappcompact
    displayName: Build Android [Pre-AppCompat]
    vmImage: $(macOSXVmImage)
    targetFolder: Xamarin.Forms.ControlGallery.Android/preAppCompat
    androidProjectArguments: '/t:"Rebuild;SignAndroidPackage" /p:ANDROID_RENDERERS="PREAPPCOMPAT" /bl:$(Build.ArtifactStagingDirectory)/android-preappcompact.binlog'
    buildConfiguration: $(AndroidBuildConfiguration)
    provisionatorPath : 'build/provisioning/provisioning.csx'

- template: build/steps/build-android.yml
  parameters:
    name: android_fast
    displayName: Build Android [Fast Renderers]
    vmImage: $(macOSXVmImage)
    targetFolder: Xamarin.Forms.ControlGallery.Android/newRenderers/
    androidProjectArguments: '/t:"Rebuild;SignAndroidPackage" /p:ANDROID_RENDERERS="FAST" /bl:$(Build.ArtifactStagingDirectory)/android-newrenderers.binlog'
    buildConfiguration: $(AndroidBuildConfiguration)
    provisionatorPath : 'build/provisioning/provisioning.csx'

- template: build/steps/build-osx.yml
  parameters:
    vmImage: $(macOSXVmImage)
    name: osx
    buildForVS2017: 'false'
    displayName: 'OSX Phase'

- template: build/steps/build-osx.yml
  parameters:
    vmImage: 'macOS-10.14'
    name: osx_2017
    buildForVS2017: 'true'
    displayName: 'OSX Phase 2017'

- job: nuget_pack
  workspace:
    clean: all
  displayName: Nuget Phase
  dependsOn:
   - win
  condition: succeeded()
  pool:
    name: $(vs2019VmPool)
    vmImage: $(vs2019VmImage)
  variables:
    FormsIdAppend: ''
    buildConfiguration: $(DefaultBuildConfiguration)
    nugetPackageVersion : $[ dependencies.win.outputs['debug.winbuild.xamarinformspackageversion'] ]
  steps:
     - template: build/steps/build-nuget.yml

  # only sign using the private server
- ${{ if eq(variables['System.TeamProject'], 'devdiv') }}:
  - job: nuget_sign
    displayName: Sign Phase
    dependsOn: nuget_pack
    pool:
      name: $(signVmPool)
    steps:
      - template: build/steps/build-sign.yml
    condition: and(succeeded(), or(eq(variables['Sign'], 'true'), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'],'refs/tags/'))))

