variables:
- name: DefaultBuildConfiguration
  value: Debug
- name: DefaultBuildPlatform
  value: 'any cpu'
- name: ApkName
  value: AndroidControlGallery.AndroidControlGallery.apk
- name: IpaName
  value: XamarinFormsControlGalleryiOS.ipa
- name: SolutionFile
  value: Xamarin.Forms.sln
- name: BuildVersion
  value: $[counter('nuget-counter', 126)]
- name: BuildVersion42
  value: $[counter('xf-nuget-counter', 992000)]
- name: BuildVersion43
  value: $[counter('xf-nuget-counter', 992000)]
- name: BuildVersion44
  value: $[counter('xf-nuget-counter', 992000)]
- name: NUGET_VERSION
  value: 5.4.0
- name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
  value: true
- name: DOTNET_VERSION
  value: 3.1.100

resources:
  repositories:
    - repository: xamarin-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin

trigger:
  branches:
    include:
    - master
    - 3.*
    - 4.*
  tags:
    include:
    - '*'
  paths:
    exclude:
    - README.md

pr:
  autoCancel: false
  branches:
    include:
    - master
    - 4.*
    - 3.*

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master

stages:
  - stage: windows
    displayName: Build Windows
    jobs:
    - template: build/steps/build-windows.yml
      parameters:
        name: win
        displayName: Build Windows Phase
        vmImage: $(vs2019VmImage)
        vmPool: $(vs2019VmPool)
        provisionatorPath : 'build/provisioning/provisioning.csx'
    - job: nuget_pack
      workspace:
        clean: all
      dependsOn:
        - win
      displayName: Nuget Phase
      condition: succeeded()
      pool:
        name: $(vs2019VmPool)
        vmImage: $(vs2019VmImage)
      variables:
        FormsIdAppend: ''
        buildConfiguration: $(DefaultBuildConfiguration)
        nugetPackageVersion : $[ dependencies.win.outputs['debug.winbuild.xamarinformspackageversion'] ]
      steps:
        - template: build/steps/build-nuget.yml

  - stage: android
    displayName: Build Android
    ${{ if eq(variables['System.TeamProject'], 'devdiv') }}:
      dependsOn: windows
    ${{ if eq(variables['System.TeamProject'], 'public') }}:
      dependsOn: []
    jobs:
      - template: build/steps/build-android.yml
        parameters:
          vmImage: $(macOSXVmImage)
          provisionatorPath : 'build/provisioning/provisioning.csx'

  - stage: build_osx
    displayName: Build OSX
    ${{ if eq(variables['System.TeamProject'], 'devdiv') }}:
      dependsOn: windows
    ${{ if eq(variables['System.TeamProject'], 'public') }}:
      dependsOn: []
    jobs:
      - job: osx
        workspace:
          clean: all
        displayName: OSX Phase
        strategy:
          matrix:
            BuildForVS2017:
              buildForVS2017:  'true'
              imageName : 'macOS-10.14'
            BuildForVS2019:
              buildForVS2017:  'false'
              imageName : 'macOS-10.14'
        pool:
          vmImage: $(imageName)
          demands:
            - sh
            - msbuild
            - Xamarin.iOS
        variables:
          provisionator.osxPath : 'build/provisioning/provisioning.csx'
          buildConfiguration: $(DefaultBuildConfiguration)
          iOSCertSecureFileName: 'Xamarin Forms iOS Certificate.p12'
          iOSProvisioningSecureFileName: 'Xamarin Forms iOS Provisioning.mobileprovision'
          buildForVS2017: $(buildForVS2017)
        steps:
          - template: build/steps/build-osx.yml

  # only sign using the private server
  - ${{ if eq(variables['System.TeamProject'], 'devdiv') }}:
    - stage: nuget_signing
      dependsOn: windows
      displayName: Sign Nuget
      jobs:
        - job: nuget_sign
          displayName: Sign Phase
          pool:
            name: $(signVmImage)
          steps:
            - template: build/steps/build-sign.yml
          condition: and(succeeded(), or(eq(variables['Sign'], 'true'), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'],'refs/tags/'))))


