name: Daily code format check
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * * # Every day at midnight (UTC)

permissions:
  pull-requests: write
  contents: write

jobs:
  dotnet-format:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 8.x

      - name: Run dotnet format
        run: dotnet format .\Microsoft.Maui.sln --no-restore --exclude Templates/src --exclude-diagnostics CA1822
    
      - name: Commit files
        if: steps.format.outputs.has-changes == 'true'
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -a -m 'Automated dotnet-format update'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: '[housekeeping] Automated PR to fix formatting errors'
          body: |
            Automated PR to fix formatting errors
          committer: GitHub <noreply@github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          labels: |
            t/housekeeping ♻︎
            area-infrastructure
          assignees: rmarinho, jsuarezruiz
          reviewers: rmarinho, jsuarezruiz
          branch: housekeeping/fix-codeformatting
          base: main
