name: PR code format check - push results
on:
  workflow_run:
    workflows: ["PR code format check"]
    types:
      - completed

permissions:
  pull-requests: write
  contents: write
  
jobs:
  push-and-notify:
    name: Push autoformatted code and notify user
    runs-on: ubuntu-latest
    if: >
      github.repository_owner == 'dotnet' &&
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: 'Push autoformatted patch'
        uses: rolfbjarne/autoformat-push@v0.5
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          commentContents: 'Thank you for your pull request. We are auto-formatting your source code to follow our code guidelines.'
